name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Generate Snake
        uses: Platane/snk@v4
        with:
          github_user_name: annikaasinha
          outputs: dist/snake.svg
      - name: Upload Snake
        uses: actions/upload-artifact@v4
        with:
          name: snake.svg
          path: dist/snake.svg
