name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3  # ✅ Use v3 instead of v2
        with:
          github_user_name: annikaasinha

      - name: Upload Snake
        uses: actions/upload-artifact@v4  # ✅ Ensure v4 is used
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg  # ✅ Corrected path
